server:
  port: 9000


spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive-db
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/reactive-db
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"


